### PR TITLE
add an interactive menu using inquire

### PR DESCRIPTION
**Pull request by melMass**
# Description

_(Thank you for improving Nushell. Please, check our [contributing guide](../CONTRIBUTING.md) and talk to the core team before making major changes.)_

_(Description of your pull request goes here. **Provide examples and/or screenshots** if your changes affect the user experience.)_

# User-Facing Changes

_(List of all changes that impact the user experience here. This helps us keep track of breaking changes.)_

# Tests + Formatting

Don't forget to add tests that cover your changes.

Make sure you've run and fixed any issues with these commands:

- `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- `cargo test --workspace` to check that all tests pass

> **Note**
> from `nushell` you can also use the `toolkit` as follows
> ```bash
> use toolkit.nu  # or use an `env_change` hook to activate it automatically
> toolkit check pr
> ```

# After Submitting

If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.

### CODE REVIEW

**Comment by fdncred** [comment]
Whatever happened to this?

**Comment by melMass** [comment]
> Whatever happened to this?

I posted the blockers I had in the thread on discord. Basically I did not manage to wrap my head around how to take a nushell closure and "execute" it properly in the rust context (to add support for the validation etc...)

**Comment by fdncred** [comment]
What would be good to see is this turned into a PR with the features we have here and maybe make it a subcommand for the `input` command like `input list` or some such thing. Even though this doesn't do everything we want it to do yet, it's a good improvement over what we have now.

Then we can continue to work on it with people who understand the finer details of what you're wanting to do.

**Comment by melMass** [comment]
Yep good point I did not think about making a sucommand to input. So you say keeping it simple for now: accept lists, return list or value and tackle the closures in a second time

**Comment by fdncred** [comment]
> So you say keeping it simple for now ...

Yup. I think a lot of people get hung up with making the perfect PR. In nushell, we can be like that sometimes, but most of the time we're about doing incremental work. Let's make it a little bit better with each PR and just continue working on it. I think this is more than a "little bit" better. The only thing that worries me is that there is a new dependency.

We may need to remove the old dependency and replace it's functionality with this one. I just have to think about what the old one is called.

Update: `dialoguer` is the current crate we use for this type of thing. I'm not sure where we use it but *if* the crate we're using here is better, we should replace dialoguer.

**Comment by fdncred** [comment]
I just filed an issue in the `inquire` repo. I can't get any of the samples working right.

**Comment by melMass** [comment]
> Update: `dialoguer` is the current crate we use for this type of thing. I'm not sure where we use it but *if* the crate we're using here is better, we should replace dialoguer.

Yep we briefly talked about that back then, I'm familiar with dialoguer that I use in multiple project so I might be more inclined to just change the dep of this PR.
I will look into all this a bit later today and let you know on Discord

**Comment by fdncred** [comment]
> I will look into all this a bit later today and let you know on Discord

sounds good. thanks.

**Comment by fdncred** [comment]
Looking good!

**Pull request closed without merging**
